//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }

        [DisplayName("Account ID")] 
        public int AccountID { get; set; }

        [Required(ErrorMessage = "Account Number is required.")]
        [StringLength(20, ErrorMessage = "Account Number cannot exceed 20 characters.")]
        [DisplayName("Account Number")]
        public string AccountNumber { get; set; }

        [Required(ErrorMessage = "Account Type is required.")]
        [StringLength(50, ErrorMessage = "Account Type cannot exceed 50 characters.")]
        [DisplayName("Account Type")]
        public string AccountType { get; set; }

        [Required(ErrorMessage = "Account Balance is required.")]
        [Range(0, double.MaxValue, ErrorMessage = "Account Balance must be a non-negativevalue.")]
        [DisplayName("Account Balance")]
        public Nullable<decimal> AccountBalance { get; set; }

        [Required(ErrorMessage = "Interest Rate is required.")]
        [Range(0, 100, ErrorMessage = "Interest Rate must be between 0 and 100.")]
        [DisplayName("Interest Rate")]
        public Nullable<decimal> InterestRate { get; set; }

        [Required(ErrorMessage = "Account Status is required.")]
        [StringLength(20, ErrorMessage = "Account Status cannot exceed 20 characters.")]
        [DisplayName("Account Status")]
        public string AccountStatus { get; set; }

        [Required(ErrorMessage = "Date Opened is required.")]
        [DataType(DataType.DateTime, ErrorMessage = "Invalid Date format.")]
        [DisplayName("Date Opened")]
        public Nullable<System.DateTime> DateOpened { get; set; }

        [Required(ErrorMessage = "Last Transaction Date is required.")]
        [DataType(DataType.DateTime, ErrorMessage = "Invalid Date format.")]
        [DisplayName("Last Transaction Date")]
        public Nullable<System.DateTime> LastTransactionDate { get; set; }

        [Required(ErrorMessage = "User ID is required.")]
        [DisplayName("User ID")]
        public Nullable<int> UserID { get; set; }

        [Required(ErrorMessage = "Branch ID is required.")]
        [DisplayName("Branch ID")]
        public Nullable<int> BranchID { get; set; }

        [Required(ErrorMessage = "Holder Type ID is required.")]
        [DisplayName("Account Holder Type ID")]
        public Nullable<int> HolderTypeID { get; set; }

        [Required(ErrorMessage = "Rate Type ID is required.")]
        [DisplayName("Interest Rate Type ID")]
        public Nullable<int> RateTypeID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual AccountHolderType AccountHolderType { get; set; }
        public virtual InterestRateType InterestRateType { get; set; }
        public virtual User User { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
