//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Bill
    {
        [DisplayName("Bill ID")]
        public int BillID { get; set; }

        [Required(ErrorMessage = "Biller Name is required.")]
        [StringLength(100, ErrorMessage = "Biller Name cannot exceed 100 characters.")]
        [DisplayName("Biller Name")]
        public string BillerName { get; set; }

        [Required(ErrorMessage = "Bill Type is required.")]
        [StringLength(50, ErrorMessage = "Bill Type cannot exceed 50 characters.")]
        [DisplayName("Bill Type")]
        public string BillType { get; set; }

        [Required(ErrorMessage = "Account Number is required.")]
        [StringLength(20, ErrorMessage = "Account Number cannot exceed 20 characters.")]
        [DisplayName("Account Number")]
        public string AccountNumber { get; set; }

        [Required(ErrorMessage = "Amount is required.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0.")]
        public Nullable<decimal> Amount { get; set; }

        [Required(ErrorMessage = "Due Date is required.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Due Date")]
        public Nullable<System.DateTime> DueDate { get; set; }

        [Required(ErrorMessage = "UserID is required.")]
        [DisplayName("User ID")]
        public Nullable<int> UserID { get; set; }

        public virtual User User { get; set; }
    }
}
