//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class CreditCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditCard()
        {
            this.Payments = new HashSet<Payment>();
        }

        [DisplayName("Credit Card ID")]
        public int CreditCardID { get; set; }

        [Required(ErrorMessage = "Credit Card Number is required.")]
        [StringLength(16, MinimumLength = 16, ErrorMessage = "Credit Card Number must be 16 characters.")]
        [DisplayName("Credit Card Number")]
        public string CreditCardNumber { get; set; }

        [Required(ErrorMessage = "Cardholder Name is required.")]
        [StringLength(100, ErrorMessage = "Cardholder Name cannot exceed 100 characters.")]
        [DisplayName("Card Holder Name")]
        public string CardholderName { get; set; }

        [Required(ErrorMessage = "Expiry Date is required.")]
        [DataType(DataType.Date)]
        [DisplayName("Expiry Date")]
        public Nullable<System.DateTime> ExpiryDate { get; set; }

        [Required(ErrorMessage = "CVV is required.")]
        [StringLength(4, MinimumLength = 3, ErrorMessage = "CVV must be 3 or 4 characters.")]
        public string CVV { get; set; }

        [Required(ErrorMessage = "Credit Limit is required.")]
        [Range(0, 999999999, ErrorMessage = "Credit Limit must be between 0 and 999999999.")]
        [DisplayName("Credit Limit")]
        public Nullable<decimal> CreditLimit { get; set; }

        [Required(ErrorMessage = "Available Credit is required.")]
        [Range(0, 999999999, ErrorMessage = "Available Credit must be between 0 and 999999999.")]
        [DisplayName("Available Credit")]
        public Nullable<decimal> AvailableCredit { get; set; }

        [Required(ErrorMessage = "UserID is required.")]
        [DisplayName("User ID")]
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
