//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Loan
    {
        [DisplayName("Loan ID")]
        public int LoanID { get; set; }

        [Required(ErrorMessage = "Loan Type is required.")]
        [StringLength(100, ErrorMessage = "Loan Type cannot exceed 100 characters.")]
        [DisplayName("Loan Type")]
        public string LoanType { get; set; }

        [Required(ErrorMessage = "Loan Amount is required.")]
        [Range(0, double.MaxValue, ErrorMessage = "Loan Amount must be a positive value.")]
        [DisplayName("Loan Amount")]
        public Nullable<decimal> LoanAmount { get; set; }

        [Required(ErrorMessage = "Interest Rate is required.")]
        [Range(0, 100, ErrorMessage = "Interest Rate must be between 0 and 100.")]
        [DisplayName("Interest Rate")]
        public Nullable<decimal> InterestRate { get; set; }

        [Required(ErrorMessage = "Loan Term is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "Loan Term must be a positive value.")]
        [DisplayName("Loan Term")]
        public Nullable<int> LoanTerm { get; set; }

        [Required(ErrorMessage = "Start Date is required.")]
        [DataType(DataType.Date, ErrorMessage = "Invalid Date format.")]
        [DisplayName("Start Date")]
        public Nullable<System.DateTime> StartDate { get; set; }

        [Required(ErrorMessage = "End Date is required.")]
        [DataType(DataType.Date, ErrorMessage = "Invalid Date format.")]
        [DisplayName("End Date")]
        public Nullable<System.DateTime> EndDate { get; set; }

        [Required(ErrorMessage = "User ID is required.")]
        [DisplayName("User ID")]
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
