//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Payment
    {
        [DisplayName("Payment ID")]
        public int PaymentID { get; set; }

        [Required(ErrorMessage = "Payment Type is required.")]
        [StringLength(50, ErrorMessage = "Payment Type cannot exceed 50 characters.")]
        [DisplayName("Payment Type")]
        public string PaymentType { get; set; }

        [Required(ErrorMessage = "Amount Paid is required.")]
        [Range(0, double.MaxValue, ErrorMessage = "Amount Paid must be a positive value.")]
        [DisplayName("Amount Paid")]
        public Nullable<decimal> AmountPaid { get; set; }

        [Required(ErrorMessage = "Payment Date is required.")]
        [DataType(DataType.DateTime, ErrorMessage = "Invalid Date format.")]
        [DisplayName("Payment Date")]
        public Nullable<System.DateTime> PaymentDate { get; set; }

        [StringLength(200, ErrorMessage = "Description cannot exceed 200 characters.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Credit Card ID is required.")]
        [DisplayName("Credit Card ID")]
        public Nullable<int> CreditCardID { get; set; }

        [Required(ErrorMessage = "User ID is required.")]
        [DisplayName("User ID")]
        public Nullable<int> UserID { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual User User { get; set; }
    }
}
