//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class SecurityQuestion
    {
        [DisplayName("Question ID")]
        public int QuestionID { get; set; }

        [Required(ErrorMessage = "Security Question is required.")]
        [StringLength(200, ErrorMessage = "Security Question cannot exceed 200 characters.")]
        [DisplayName("Security Question")]
        public string SecurityQuestion1 { get; set; }

        [Required(ErrorMessage = "Answer is required.")]
        [StringLength(100, ErrorMessage = "Answer cannot exceed 100 characters.")]
        public string Answer { get; set; }

        [Required(ErrorMessage = "User ID is required.")]
        [DisplayName("User ID")]
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
