//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Transaction
    {
        [DisplayName("Transaction ID")]
        public int TransactionID { get; set; }

        [Required(ErrorMessage = "Transaction Type is required.")]
        [StringLength(50, ErrorMessage = "Transaction Type cannot exceed 50 characters.")]
        [DisplayName("Transaction Type")]
        public string TransactionType { get; set; }

        [Required(ErrorMessage = "Amount is required.")]
        [Range(0, double.MaxValue, ErrorMessage = "Amount must be a positive value.")]
        public Nullable<decimal> Amount { get; set; }

        [Required(ErrorMessage = "Transaction Date is required.")]
        [DataType(DataType.DateTime, ErrorMessage = "Invalid Date format.")]
        [DisplayName("Transaction Date")]
        public Nullable<System.DateTime> TransactionDate { get; set; }

        [StringLength(200, ErrorMessage = "Description cannot exceed 200 characters.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Source Account Number is required.")]
        [DisplayName("Account Number")]
        public Nullable<int> SourceAccountNumber { get; set; }

        [Required(ErrorMessage = "Destination Account Number is required.")]
        [StringLength(20, ErrorMessage = "Destination Account Number cannot exceed 20 characters.")]
        [DisplayName("Transfer To")]
        public string DestinationAccountNumber { get; set; }

        [Required(ErrorMessage = "User ID is required.")]
        [DisplayName("User ID")]
        public Nullable<int> UserID { get; set; }

        [Required(ErrorMessage = "Status ID is required.")]
        [DisplayName("Status ID")]
        public Nullable<int> StatusID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TransactionStatu TransactionStatu { get; set; }
        public virtual User User { get; set; }
    }
}
